DROP TABLE IF EXISTS NOTAS;
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENIA VARCHAR(150) NOT NULL,
    ACTIVO INT NOT NULL,
    FECHA_CREACION TIMESTAMP NOT NULL,
    AUTHORITIES VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE NOTAS (
    ID_NOTA INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    CONTENIDO TEXT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);


INSERT INTO USUARIO (USUARIO, CONTRASENIA, ACTIVO, FECHA_CREACION, AUTHORITIES)
VALUES ('USUARIO1', '$2a$10$eJsKvU59Zj3GhWlsMVeK6OQ.PPL0d21zX3330.wv.aPsWklOxTMwy', 1, '2024-06-21 22:18:02', 'ADMIN');
